name: automorph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.3.1
    - torchvision==0.18.1
    - torchaudio==2.3.1
    - certifi
    - numpy
    - matplotlib==3.9.0
    - opencv-python-headless==4.10.0.84
    - pandas==2.2.0
    - Pillow==10.3.0
    - pyarrow==19.0.1
    - tqdm==4.66.4
    - scipy==1.14.0
    - scikit-image==0.24.0
    - fsspec==2025.3.0
    - h5py==3.11.0
    - efficientnet_pytorch==0.7.1

# conda remove --name automorph --all
# conda env create -f environment.yml
